name: Specs

on: [push]

jobs:
  nodejs:
    name: NodeJS Buildpipeline ${{ matrix.node-version }}
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
      - steps: yarn install
      - steps: yarn build
      - steps: yarn test    
  