name: Specs

on: [push]

jobs:   
  php:
    name: Tests on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.1, 8.2]
        node-version: [18.x, 20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP with composer
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, fileinfo, mysql, libxml, xml, xmlwriter, dom, tokenizer, filter, json, phar, pcre, openssl, pdo, intl, curl

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: cd api && composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Setup test environment
        run: |
          cd api && php -r "copy('.env.example', '.env.testing');"

      - name: Run tests
        run: cd api && php artisan key:generate && php artisan test
