name: Specs

on: [push]

jobs:
  php:
    name: Tests on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.2, 8.3]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP with composer
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, fileinfo, mysql, libxml, xml, xmlwriter, dom, tokenizer, filter, json, phar, pcre, openssl, pdo, intl, curl

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: cd api && composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Setup test environment
        run: |
          cd api && php -r "copy('.env.example', '.env');"
      - name: Run tests
        run: cd api && php artisan key:generate && php artisan test

  nodejs:
    name: NodeJS build-pipeline ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: 'echo ''{"en": {}}'' > frontend/i18n/en.json'
      - run: npm run i18n
      - run: cd frontend && npm install
      - run: cd frontend && npm run build
      - run: cd frontend && npm run test
